name: CI/CD Pipeline for TodoApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: todoapp
      # DOCKER_REGISTRY: docker.io # <--- Удаляем, так как пушим в GCR
      GCP_PROJECT_ID: your-gcp-project-id  # <--- Добавляем Project ID для GCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and skip tests
        run: mvn -B package -DskipTests --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Cloud Authenticate for GCR
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image to GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest # <--- Пушим в GCR

      - name: Notify on build and push result
        run: echo "Docker image build and push to GCR completed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    environment: production
    env:
      IMAGE_NAME: todoapp
      GCP_PROJECT_ID: your-gcp-project-id  # <--- Вставьте сюда ID вашего Google Cloud проекта
      GCP_REGION: us-central1             # <--- Выберите подходящий регион Cloud Run
      CLOUD_RUN_SERVICE_NAME: todoapp-service # <--- Название вашего сервиса Cloud Run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --project ${{ env.GCP_PROJECT_ID }}

      - name: Notify on deployment result
        run: echo "Deployment to Google Cloud Run completed successfully!"